### ISSUE TITLE
SDK doesn't sync in project

### ISSUE THREAD

**Issue by verygreenboi** [PaystackHQ/paystack-android#23]
I included the library in my build.gradle file and my project has since stopped syncing. This is the error I get

```
Error:/xxx/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:473 resource android:attr/foregroundInsidePadding is private

Error:java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.AaptException: AAPT2 link failed:

Error:com.android.builder.internal.aapt.AaptException: AAPT2 link failed:

Error:Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt
```

When I remove the compile line, my project syncs up fine again.

This is how my build looks like:

```
compileSdkVersion 25
buildToolsVersion "25.0.2"
minSdkVersion 21
targetSdkVersion 25
```

**Comment by ibrahimlawal** [comment]
Hey Thompson,

Are you on Skype? Or TeamViewer.

Let's get on a call to troubleshoot this together. You should also report here: https://github.com/PaystackHQ/paystack-android/issues so the community can provide some pointers.

Thank you for choosing Paystack.

Thanks!


—
Ibrahim Lawal | Customer Success Engineer


@ibrahimlawal on Payslack | Join us via http://slack.paystack.com
@ibrahimlawal on GitHub
@ibrahimlawal on Twitter
Skype:profibro


Paystack Payments Limited
3A, Ladoke Akintola Street, Ikeja GRA.
Office Phone: +234 908 566 2909




www.paystack.com 

--- original message ---
On Tue, Jun 13, 2017 at 01:34 pm, <notifications@github.com> Thompson Edolo wrote:


I included the library in my build.gradle file and my project has since stopped syncing. This is the error I get
Error:/xxx/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:473 resource android:attr/foregroundInsidePadding is private

Error:java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.AaptException: AAPT2 link failed:

Error:com.android.builder.internal.aapt.AaptException: AAPT2 link failed:

Error:Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt

When I remove the compile line, my project syncs up fine again.

This is how my build looks like:
compileSdkVersion 25
buildToolsVersion "25.0.2"
minSdkVersion 21
targetSdkVersion 25

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by verygreenboi** [comment]
Hello Ibrahim.

Yes, I'm on skype. Would love to call you up as soon as it is convenient for you.

**Comment by ibrahimlawal** [comment]
Hey Thompson,

Still awaiting your Skype request. My ID is skype:profibro

Thank you for choosing Paystack.

Thanks!


—
Ibrahim Lawal | Customer Success Engineer


@ibrahimlawal on Payslack | Join us via http://slack.paystack.com
@ibrahimlawal on GitHub
@ibrahimlawal on Twitter
Skype:profibro


Paystack Payments Limited
3A, Ladoke Akintola Street, Ikeja GRA.
Office Phone: +234 908 566 2909




www.paystack.com 

--- original message ---
On Tue, Jun 13, 2017 at 03:38 pm, <notifications@github.com> Thompson Edolo wrote:


Hello Ibrahim.

Yes, I'm on skype. Would love to call you up as soon as it is convenient for you.

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by ighotouch** [comment]
Hello Having same issue using Android 3.0 with classpath 'com.android.tools.build:gradle:3.0.0-alpha3'

**Comment by verygreenboi** [comment]
@ighotouch So I solved this issue by going back to Android Studio 2.3 and starting a fresh project then copying my code over.

**Comment by ighotouch** [comment]
@verygreenboi that was an over kill, you should have just ported your grade build back to 2.3.3, as the issue was with grade version and not android studio itself.

**Comment by wilburt** [comment]
This has not been fixee. It's still happening as at com.android.tools.build:gradle:3.0.0-beta4.

**Comment by ibrahimlawal** [comment]
Once we have a stable version for gradle:3.0 , we will make it fully compatible.

**Comment by ibrahimlawal** [comment]
@verygreenboi @wilburt @ighotouch fixed now that gradle:3.0 has been released as stable. Thank you for choosing Paystack 👍

**Comment by verygreenboi** [comment]
In the future, I'd hope that a branch will be created for beta version so that we can build alongside new releases of gradle and other dependencies.

Regardless, great work guys.

**Comment by Elvis10ten** [comment]
Issue still exists. I am using version 3.0.7 of the paystack library.

The only easy way to get around the issue was to disable AAPT2 in my gradle.properties file.

**Comment by ibrahimlawal** [comment]
@Elvis10ten please update to 3.0.9 and let me know if you are able to use the library on AAPT2 with no trouble. Thank you for choosing Paystack. Best Regards!

**Comment by ibrahimlawal** [comment]
@verygreenboi I truly never thought of that. Will make sure to do a beta branch in future.

**Comment by Elvis10ten** [comment]
Updated to 3.0.9. Using AAPT2 without any trouble. Thanks.

**Comment by alan-qbasic** [comment]
@ibrahimlawal Morning

Adding 'co.paystack.android:paystack:3.0.9' to my dependencies will suddenly tag com.android.support:appcompat-v7:25.4.0 as an error and in turn values-v26.xml  automatiacaly open up

Thank you

**Comment by devmike01** [comment]
@alan-qbasic Update your compile SDK to 27. That should solve the it.

**Comment by Jayjerome** [comment]
Added the dependency version co.paystack.android:paystack:3.0.10 and it doesn't sync... Error
Could not find common.jar

**Comment by Jayjerome** [comment]
Tried lower version but still didn't sync...
3.0.6
.
..
3.0.10

**Comment by devmike01** [comment]
Add `google()` above `jcenter()` in your root project's gradle file.

**Comment by Jayjerome** [comment]
I've done that still doesn't sync

**Comment by Jayjerome** [comment]
It finally worked thanks

**Comment by devmike01** [comment]
I'm glad it works. You're welcome.

**Comment by Jayjerome** [comment]
@devmike01 
My Java compiler just returned 5 errors
Android resource linking failed
Output:  C:\Users\Jerome\AndroidStudioProjects\Taxitime\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v26\values-v26.xml:7: error: resource android:attr/colorError not found.
C:\Users\Jerome\AndroidStudioProjects\Taxitime\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v26\values-v26.xml:11: error: resource android:attr/colorError not found.
C:\Users\Jerome\AndroidStudioProjects\Taxitime\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v26\values-v26.xml:15: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
C:\Users\Jerome\AndroidStudioProjects\Taxitime\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:520: error: resource android:attr/fontStyle not found.
C:\Users\Jerome\AndroidStudioProjects\Taxitime\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:520: error: resource android:attr/font not found.
C:\Users\Jerome\AndroidStudioProjects\Taxitime\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:520: error: resource android:attr/fontWeight not found.
error: failed linking references.

Command: C:\Users\Jerome\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.0-alpha17-4804415-windows.jar\b118d33bada9a969adfe3ddfdb367b9f\aapt2-3.2.0-alpha17-4804415-windows\aapt2.exe link -I\
        C:\Users\Jerome\AppData\Local\Android\Sdk\platforms\android-25\android.jar\
        --manifest\
        C:\Users\Jerome\AndroidStudioProjects\Taxitime\app\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
        -o\
        C:\Users\Jerome\AndroidStudioProjects\Taxitime\app\build\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
        -R\
        @C:\Users\Jerome\AndroidStudioProjects\Taxitime\app\build\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
        --auto-add-overlay\
        --java\
        C:\Users\Jerome\AndroidStudioProjects\Taxitime\app\build\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
        --proguard-main-dex\
        C:\Users\Jerome\AndroidStudioProjects\Taxitime\app\build\intermediates\legacy_multidex_aapt_derived_proguard_rules\debug\processDebugResources\manifest_keep.txt\
        --custom-package\
        com.example.jerome.taxify\
        -0\
        apk\
        --output-text-symbols\
        C:\Users\Jerome\AndroidStudioProjects\Taxitime\app\build\intermediates\symbols\debug\R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.0-alpha17-4804415-windows Daemon #0


What could be the problem?

**Comment by devmike01** [comment]
@Jayjerome You're setting some wrong resource attributes in your resource folder. Some of the attributes causing the error are `colorError`, `fontWeight`, `font` and so on. Also, this question is off-topic and should be posted on generic programming Q&A platform like [StackOverflow](stackoverflow.com)

However, this thread should be be closed and mark as fixed. @ibrahimlawal

**Comment by Jayjerome** [comment]
Alright but how do I go about this error log
Configuration 'androidTestCompile' is obsolete and has been replaced with 'androidTestImplementation' and 'androidTestApi'
Is this an issue I should be concerned over or I should just ignore and move on?

**Comment by Jayjerome** [comment]
@devmike01  after successful sync my project now gives error in most part of my code. I've tried cleaning my project and even tried invalidate caches and restart but the program still give those error lines although these lines don't pop up as error in the log cat. Please help

**Comment by aapeliltd** [comment]
i am using nativescript with angular as template. i tried install nativescript-paystack as:

tns add plugin nativescript-paystack
it was successfully added. i tried to run my app again as tns run android. and my app will not run again and i when i tried remove as ( tns remove plugin nativescript-paystack) and my app will run again fine. please see details of the error below. thanks

C:\mobileprojects\fiwonpay>tns plugin add nativescript-paystack
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

nativescript-paystack@0.2.3
added 1 package in 58.986s
Successfully installed plugin nativescript-paystack.
C:\mobileprojects\fiwonpay>tns run android
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Executing before-liveSync hook from C:\mobileprojects\fiwonpay\hooks\before-liveSync\nativescript-angular-sync.js
Executing before-watchPatterns hook from C:\mobileprojects\fiwonpay\hooks\before-watchPatterns\nativescript-dev-sass.js
Executing before-watchPatterns hook from C:\mobileprojects\fiwonpay\hooks\before-watchPatterns\nativescript-dev-typescript.js
Executing before-watchPatterns hook from C:\mobileprojects\fiwonpay\hooks\before-watchPatterns\nativescript-dev-webpack.js
Executing before-watch hook from C:\mobileprojects\fiwonpay\hooks\before-watch\nativescript-dev-sass.js
Found peer node-sass
Executing before-watch hook from C:\mobileprojects\fiwonpay\hooks\before-watch\nativescript-dev-typescript.js
Found peer TypeScript 2.7.2
Executing before-watch hook from C:\mobileprojects\fiwonpay\hooks\before-watch\nativescript-dev-webpack.js
Executing before-shouldPrepare hook from C:\mobileprojects\fiwonpay\hooks\before-shouldPrepare\nativescript-dev-webpack.js
Executing before-prepare hook from C:\mobileprojects\fiwonpay\hooks\before-prepare\nativescript-dev-sass.js
Hook skipped because either bundling or livesync is in progress.
Executing before-prepare hook from C:\mobileprojects\fiwonpay\hooks\before-prepare\nativescript-dev-typescript.js
Hook skipped because either bundling or livesync is in progress.
Preparing project...
Executing before-prepareJSApp hook from C:\mobileprojects\fiwonpay\hooks\before-prepareJSApp\nativescript-dev-webpack.js
Successfully prepared plugin nativescript-angular for android.
Successfully prepared plugin nativescript-filter-select for android.
Successfully prepared plugin nativescript-loading-indicator for android.
Successfully prepared plugin nativescript-paystack for android.
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin nativescript-intl for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Unable to apply changes on device: 4ccfcc14. Error is: Failed to build plugin nativescript-paystack :
Error: Command gradlew.bat failed with exit code 1 Error output:
C:\Users\ME.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.0.aar\2c2824cca5eb767c914e9356717041fd\res\values-v26\values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.

C:\Users\ME.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.0.aar\2c2824cca5eb767c914e9356717041fd\res\values-v26\values-v26.xml:13:5-16:13: AAPT: error: resource android:attr/colorError not found.

C:\Users\ME.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.0.aar\2c2824cca5eb767c914e9356717041fd\res\values-v26\values-v26.xml:17:5-93: AAPT: error: style attribute 'android:attr/keyboardNavigationCluster' not found.

C:\Users\ME.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.0.aar\2c2824cca5eb767c914e9356717041fd\res\values\values.xml:252:5-69: AAPT: error: resource android:attr/fontStyle not found.

C:\Users\ME.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.0.aar\2c2824cca5eb767c914e9356717041fd\res\values\values.xml:252:5-69: AAPT: error: resource android:attr/font not found.

C:\Users\ME.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.0.aar\2c2824cca5eb767c914e9356717041fd\res\values\values.xml:252:5-69: AAPT: error: resource android:attr/fontWeight not found.

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':verifyReleaseResources'.
com.android.ide.common.process.ProcessException: Failed to execute aapt

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 2m 47s
.
Executing after-watch hook from C:\mobileprojects\fiwonpay\hooks\after-watch\nativescript-dev-sass.js
Executing after-watch hook from C:\mobileprojects\fiwonpay\hooks\after-watch\nativescript-dev-typescript.js
Stopping tsc watch
Executing after-watch hook from C:\mobileprojects\fiwonpay\hooks\after-watch\nativescript-dev-webpack.js
